### ISSUE TITLE
Spark Broadcast exceeding executor memory with large training data set

### ISSUE THREAD

**Issue by shaunswanson** [databricks/spark-sklearn#101] opened 2019-01-23 00:47 UTC
My X variable is between 1-4 GB. The pre_dispatch arg when initializing GridSearchCV doesn't appear to be used or have any effect, preventing me from parallelizing a decently-sized param_grid in my Spark cluster.

The X variable is being broadcast to all combinations of param_grid (48 in our case), causing memory to fill up.

https://github.com/databricks/spark-sklearn/blob/705401005de4c951604645e737ea303a1788709f/python/spark_sklearn/grid_search.py#L307

Is there a way that the code above could pull the broadcast variables, rather than pushing them eagerly to every task?

**Comment by srowen** [comment] 2019-01-23 00:54
Yeah pre_dispatch doesn't have any effect; it's there to make this a drop-in replacement for scikit's implementation, but the execution context is quite different.

A broadcast will only be copied once to each executor in Spark. Spark effectively 'pulls' but it won't matter as all the tasks need this data. The grid here reuses the single instance of the X broadcast. I don't think that's the issue unless there's something subtler at work.

However this fix might be relevant, which would come in the next version: https://github.com/databricks/spark-sklearn/commit/03df085f8f6dc87162040c7dbf6ba78ecd33910c

Else, maybe you can say more about what runs out of memory where.

**Comment by srowen** [comment] 2019-01-28 17:00
PS I merged #100 which removes "pre_dispatch". Reopen or comment if the next release doesn't resolve this, as I think the issue is broadcasting the split indices.

**Closed by srowen** 2019-01-28 17:00 UTC

**Comment by nareshsankapelly** [comment] 2019-03-20 05:52
@srowen There is a restriction on the size of X due to cloudpickle limitations. I'm seeing the following error when the size of X exceeds 2 GB. 
PicklingError: Could not serialize broadcast: OverflowError: cannot serialize a string larger than 2 GiB

How do we use GridsearchCV with larger training datasets? 

One option I can think of is to not use broadcast variable for X and y. Instead, load this as a pandas data frame and write to a file. Every executor would read from that file.

**Comment by srowen** [comment] 2019-03-20 06:22
Yeah, in that case you would need to side-load the data somehow. This is a limitation of Spark/cloudpickle, as you say.
