### ISSUE TITLE
GridSearchCV documentation generation warnings

### ISSUE THREAD

**Issue by vlad17** [databricks/spark-sklearn#37] opened 2016-06-28 00:15 UTC
Here's the warnings from a generation run, which need to be fixed: https://gist.github.com/vlad17/5ed3d53c28474e67ccafc5e4d48a245f

**Comment by srowen** [comment] 2018-12-08 20:02
Yep, I'll fix this. The problem is the docs are just copied from scikit and not all the references are correct. Those attributes don't exist in this derived class.

**Comment by srowen** [comment] 2018-12-09 21:00
This should be resolved by https://github.com/databricks/spark-sklearn/pull/95 _except_ for the warnings about missing attributes. That's a larger issue I'm going to track separately.

**Closed by srowen** 2018-12-09 21:00 UTC
Labels: bug
